export const ALREADY_REGISTED_ERROR = ' пользователь c такими данными уже существует';
export const WRONG_EMAIL_ERROR = 'пользователь c такими данными не найден';
export const WRONG_PASSWORD_ERROR = 'неверный пароль';
export const UNAUTHTORIZE_ERROR = 'ошибка авторизации';
export const STOP_ERROR = 'нет прав доступа';
export const ERROR = 'ошибка API';
export const USER_ERROR = 'пользователь не найден';
export const FILE_ERROR = 'ошибка типа файла';
export const CONFLICT_ERROR = 'по запросу данных не найдено';